"""added profile, avatar, and games tables

Revision ID: 1ebfbbbe8123
Revises: 902f537843f2
Create Date: 2020-10-08 12:59:55.409146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebfbbbe8123'
down_revision = '902f537843f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=255), nullable=False),
    sa.Column('is_fps', sa.Boolean(), nullable=True),
    sa.Column('is_rpg', sa.Boolean(), nullable=True),
    sa.Column('is_mmo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('des', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('game')
    op.drop_table('avatars')
    # ### end Alembic commands ###
