"""added profile, avatar, and games tables

Revision ID: 2c7a8a32139a
Revises: 1ebfbbbe8123
Create Date: 2020-10-08 13:03:47.858932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7a8a32139a'
down_revision = '1ebfbbbe8123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=255), nullable=False),
    sa.Column('is_fps', sa.Boolean(), nullable=True),
    sa.Column('is_rpg', sa.Boolean(), nullable=True),
    sa.Column('is_mmo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_fps', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_rpg', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_mmo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='game_pkey')
    )
    op.drop_table('games')
    # ### end Alembic commands ###
